### PR TITLE
Add datable

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add datable, to find easy the oldest release 
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes 
| How to test?      | 
| Possible impacts? | 

Screenshot - 2022-08-18T150221 485

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]
Nice! :)

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Tested on my localhost

**Comment by matks** [comment]
Thank you @okom3pom and sorry for the late approval & test

**Comment by ghost** [comment]
No problem

**Pull request merged**
